Fixes missing trigger transaction props and adds experimental support for concurrent price update processing
GainsNetwork-org/nft-bot-v3 pull request #29
Opened 2023-02-18 19:32 UTC by drub0y

- Fixes trigger txns to have explicitly set nonce
- Supports concurrent price update processing

2023-02-19 07:10 UTC, 0xCrumb requested changes

2023-02-19 07:10 UTC, 0xCrumb commented on bot.js
> +		common: COMMON_TRANSACTION_PROPS,
Need to remove common. causing error in conjunction with setting chain in the object.

2023-02-19 07:10 UTC, 0xCrumb commented on bot.js
> +const COMMON_TRANSACTION_PROPS = Object.freeze({
Not necessary if we already set chainId in the object.

2023-02-19 07:10 UTC, 0xCrumb commented on bot.js
> +		common: COMMON_TRANSACTION_PROPS,
In fact for speed optimisations we only need to add nonce + chainId, the rest can go - less things to keep track of

2023-02-19 15:42 UTC, drub0y commented on bot.js
> +const COMMON_TRANSACTION_PROPS = Object.freeze({
Needed it for `hardfork`, but remembered you can just put `hardfork` on the transaction itself too.

2023-02-19 15:43 UTC, drub0y commented on bot.js
> +		common: COMMON_TRANSACTION_PROPS,
Ah, I already had `hardfork` here explicitly. I wonder why I wasn't getting the error you were getting tho. Anywho, this
should be gtg now!

2023-02-20 14:54 UTC, 0xCrumb commented
lgtm, ran locally without any problems

2023-02-24 10:22 UTC, 0xCrumb approved these changes
Ran all night without issues. Approved

2023-02-24 10:35 UTC, merged